In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [28]:
data = pd.read_csv('https://raw.githubusercontent.com/DmitryNakhimovich/ML_homework_1/master/leaf.csv', sep = ',', engine = 'python')

In [29]:
data.head()

Class  Specimen_Number  Eccentricity  Aspect_Ratio  Elongation  Solidity  \
0      1                1       0.72694        1.4742     0.32396   0.98535   
1      1                2       0.74173        1.5257     0.36116   0.98152   
2      1                3       0.76722        1.5725     0.38998   0.97755   
3      1                4       0.73797        1.4597     0.35376   0.97566   
4      1                5       0.82301        1.7707     0.44462   0.97698   

   Stochastic_Convexity  Isoperimetric_Factor  Maximal_Indentation_Depth  \
0               1.00000               0.83592                   0.004657   
1               0.99825               0.79867                   0.005242   
2               1.00000               0.80812                   0.007457   
3               1.00000               0.81697                   0.006877   
4               1.00000               0.75493                   0.007428   

   Lobedness  Average_Intensity  Average_Contrast  Smoothness  Third_moment  \
0   0.003947           0.047790          0.127950    0.016108      0.005232   
1   0.005002           0.024160          0.090476    0.008119      0.002708   
2   0.010121           0.011897          0.057445    0.003289      0.000921   
3   0.008607           0.015950          0.065491    0.004271      0.001154   
4   0.010042           0.007938          0.045339    0.002051      0.000560   

   Uniformity  Entropy  
0    0.000275  1.17560  
1    0.000075  0.69659  
2    0.000038  0.44348  
3    0.000066  0.58785  
4    0.000024  0.34214

In [30]:
data['Class'].dtype

dtype('int64')

In [31]:
data = data.drop(['Specimen_Number'], axis = 1)

In [32]:
data['Eccentricity'].dtype

dtype('float64')

In [33]:
categorical_columns = [c for c in data.columns if data[c].dtype.name == 'int64']
numerical_columns   = [c for c in data.columns if data[c].dtype.name == 'float64']
print(categorical_columns)
print(numerical_columns)

['Class']
['Eccentricity', 'Aspect_Ratio', 'Elongation', 'Solidity', 'Stochastic_Convexity', 'Isoperimetric_Factor', 'Maximal_Indentation_Depth', 'Lobedness', 'Average_Intensity', 'Average_Contrast', 'Smoothness', 'Third_moment', 'Uniformity', 'Entropy']


In [34]:
data = data.fillna(data.median(axis = 0), axis = 0)

In [35]:
data[numerical_columns].count(axis = 0)

Eccentricity                 340
Aspect_Ratio                 340
Elongation                   340
Solidity                     340
Stochastic_Convexity         340
Isoperimetric_Factor         340
Maximal_Indentation_Depth    340
Lobedness                    340
Average_Intensity            340
Average_Contrast             340
Smoothness                   340
Third_moment                 340
Uniformity                   340
Entropy                      340
dtype: int64

In [36]:
data[categorical_columns].count(axis = 0)

Class    340
dtype: int64

In [38]:
type(data['Class'].describe())

pandas.core.series.Series

In [39]:
nonbinary_columns = categorical_columns
print(nonbinary_columns)

['Class']


In [40]:
data['Class'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], dtype=int64)

In [41]:
data_nonbinary = pd.get_dummies(data[nonbinary_columns])
print(data_nonbinary.columns)

Index(['Class'], dtype='object')


In [42]:
data_numerical = data[numerical_columns]
data_numerical.describe()

Eccentricity  Aspect_Ratio  Elongation    Solidity  \
count    340.000000    340.000000  340.000000  340.000000   
mean       0.719854      2.440210    0.513760    0.904158   
std        0.208311      2.599043    0.195583    0.114639   
min        0.117080      1.006600    0.107610    0.485490   
25%        0.550622      1.211300    0.349623    0.890667   
50%        0.763450      1.570750    0.501855    0.948130   
75%        0.895097      2.343100    0.633373    0.976897   
max        0.998710     19.038000    0.948340    0.993880   

       Stochastic_Convexity  Isoperimetric_Factor  Maximal_Indentation_Depth  \
count            340.000000            340.000000                 340.000000   
mean               0.943793              0.531234                   0.037345   
std                0.115047              0.217532                   0.038575   
min                0.396490              0.078376                   0.002837   
25%                0.966230              0.346818                   0.009521   
50%                0.992980              0.579160                   0.023860   
75%                1.000000              0.700712                   0.047834   
max                1.000000              0.858160                   0.198980   

        Lobedness  Average_Intensity  Average_Contrast  Smoothness  \
count  340.000000         340.000000        340.000000  340.000000   
mean     0.523845           0.051346          0.124535    0.017670   
std      1.039639           0.035965          0.051860    0.013755   
min      0.001464           0.005022          0.033415    0.001115   
25%      0.016500           0.022843          0.083362    0.006901   
50%      0.103615           0.042087          0.119375    0.014050   
75%      0.416433           0.073046          0.163795    0.026127   
max      7.206200           0.190670          0.280810    0.073089   

       Third_moment  Uniformity     Entropy  
count    340.000000  340.000000  340.000000  
mean       0.005928    0.000387    1.162630  
std        0.005294    0.000431    0.584854  
min        0.000229    0.000007    0.169400  
25%        0.002080    0.000102    0.718900  
50%        0.004447    0.000239    1.077450  
75%        0.008307    0.000516    1.554575  
max        0.029786    0.002936    2.708500

In [43]:
data_numerical = (data_numerical - data_numerical.mean(axis = 0))/data_numerical.std(axis = 0)

In [44]:
data = pd.concat((data_numerical, data_nonbinary), axis = 1)
data.describe()

Eccentricity  Aspect_Ratio    Elongation      Solidity  \
count  3.400000e+02  3.400000e+02  3.400000e+02  3.400000e+02   
mean  -7.836868e-17  1.025324e-16  1.182714e-15  2.612289e-15   
std    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
min   -2.893625e+00 -5.515916e-01 -2.076615e+00 -3.652049e+00   
25%   -8.123989e-01 -4.728318e-01 -8.392240e-01 -1.176756e-01   
50%    2.092823e-01 -3.345309e-01 -6.087142e-02  3.835711e-01   
75%    8.412579e-01 -3.736376e-02  6.115670e-01  6.345107e-01   
max    1.338651e+00  6.386117e+00  2.221971e+00  7.826495e-01   

       Stochastic_Convexity  Isoperimetric_Factor  Maximal_Indentation_Depth  \
count          3.400000e+02          3.400000e+02               3.400000e+02   
mean           3.811330e-15          5.956020e-16               9.404242e-17   
std            1.000000e+00          1.000000e+00               1.000000e+00   
min           -4.757231e+00         -2.081802e+00              -8.945736e-01   
25%            1.950257e-01         -8.477669e-01              -7.212939e-01   
50%            4.275402e-01          2.203195e-01              -3.495692e-01   
75%            4.885590e-01          7.791005e-01               2.719098e-01   
max            4.885590e-01          1.502892e+00               4.190168e+00   

          Lobedness  Average_Intensity  Average_Contrast    Smoothness  \
count  3.400000e+02       3.400000e+02      3.400000e+02  3.400000e+02   
mean   3.160870e-16      -8.450756e-16     -8.228712e-17  2.821273e-16   
std    1.000000e+00       1.000000e+00      1.000000e+00  1.000000e+00   
min   -5.024633e-01      -1.288046e+00     -1.757048e+00 -1.203535e+00   
25%   -4.880009e-01      -7.925253e-01     -7.939332e-01 -7.828785e-01   
50%   -4.042074e-01      -2.574413e-01     -9.949592e-02 -2.631746e-01   
75%   -1.033170e-01       6.033490e-01      7.570472e-01  6.148668e-01   
max    6.427570e+00       3.873877e+00      3.013427e+00  4.028996e+00   

       Third_moment    Uniformity       Entropy       Class  
count  3.400000e+02  3.400000e+02  3.400000e+02  340.000000  
mean   2.089832e-16  2.559227e-16 -1.320839e-15   18.544118  
std    1.000000e+00  1.000000e+00  1.000000e+00   11.152514  
min   -1.076344e+00 -8.814640e-01 -1.698253e+00    1.000000  
25%   -7.268709e-01 -6.604173e-01 -7.587023e-01    9.000000  
50%   -2.797381e-01 -3.442725e-01 -1.456430e-01   15.000000  
75%    4.494055e-01  2.988933e-01  6.701592e-01   29.000000  
max    4.506561e+00  5.907140e+00  2.643174e+00   36.000000

In [45]:
X = data.drop(('Class'), axis = 1)
y = data['Class']
feature_names = X.columns

In [46]:
type(feature_names)

pandas.core.indexes.base.Index

In [47]:
feature_names

Index(['Eccentricity', 'Aspect_Ratio', 'Elongation', 'Solidity',
       'Stochastic_Convexity', 'Isoperimetric_Factor',
       'Maximal_Indentation_Depth', 'Lobedness', 'Average_Intensity',
       'Average_Contrast', 'Smoothness', 'Third_moment', 'Uniformity',
       'Entropy'],
      dtype='object')

In [48]:
print(X.shape)
print(y.shape)
N, d = X.shape

(340, 14)
(340,)


In [49]:
type(X)

pandas.core.frame.DataFrame

In [50]:
type(y)

pandas.core.series.Series

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

N_train, _ = X_train.shape 
N_test,  _ = X_test.shape 

print(N_train, N_test)

238 102


In [52]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 10)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [53]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [54]:
y_train_predict = knn.predict(X_train)
y_test_predict = knn.predict(X_test)

err_train = np.mean(y_train != y_train_predict)
err_test  = np.mean(y_test  != y_test_predict)

print(err_train, err_test)

0.352941176471 0.441176470588


In [55]:
err_test = 1 - knn.score(X_test, y_test)

In [56]:
err_test

0.44117647058823528

In [57]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_test_predict))

[[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0

In [58]:
from sklearn.model_selection import GridSearchCV
nnb = [1, 3, 5, 10, 15, 20, 25, 35, 45, 55]
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, param_grid = {'n_neighbors': nnb}, cv=10)
grid.fit(X_train, y_train)

best_cv_err = 1 - grid.best_score_
best_n_neighbors = grid.best_estimator_.n_neighbors
print(best_cv_err, best_n_neighbors)

C:\Users\gun95\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.331932773109 1


In [59]:
knn = KNeighborsClassifier(n_neighbors = best_n_neighbors).fit(X_train, y_train)

err_train = np.mean(y_train != knn.predict(X_train))
err_test  = np.mean(y_test  != knn.predict(X_test))

print(err_train, err_test)

0.0 0.264705882353
